version: '3'

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbit_mq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongo:
    image: mongo:latest
    environment:
        MONGO_INITDB_ROOT_USERNAME: user
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: test-task
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_main_data:/data/db

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: postgres
    environment:
      POSTGRES_DB: "test-task"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"

    ports:
      - "5433:5432"

volumes:
  rabbitmq_data:
  mongo_main_data: