controllers:
    resource:
        path: ../src/Shared/Infrastructure/Controller/
        namespace: App\Shared\Infrastructure\Controller
    type: attribute

data_controller:
    resource:
        path: ../src/AnalyticData/Infrastructure/Http/Controller/
        namespace: App\AnalyticData\Infrastructure\Http\Controller
    type: attribute